---
- name: Install apt-cache-ng
  hosts: aptcacheng
  sudo: True
  vars:
    proxy_env:
  roles:
    - apt-cache-ng-server
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_vhosts:
        - listen: "80 default_server"
          server_name: "{{ inventory_hostname }}"
          extra_parameters: |
            location / { 
              proxy_pass http://apt-cacher-ng;
              proxy_redirect off;
              proxy_buffering off;
              proxy_set_header  Host            $host;
              proxy_set_header  X-Real-IP       $remote_addr;
              proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            }
      nginx_upstreams:
        - name: apt-cacher-ng
        #strategy: "ip_hash" # "least_conn", etc.
          servers: {
            "localhost:9999"
          }
